import Head from "next/head";
import Info from "../components/home/Info";
import Layout from "../components/Layout";

export default function Home() {
    return (
        <Layout>
            <Head>
                <title>포트폴리오</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Info />
        </Layout>
    );
}
