import Head from "next/head";
import React from "react";
import Layout from "../components/layout";

export default function project() {
    return (
        <Layout>
            <Head>
                <title>포트폴리오</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            project
        </Layout>
    );
}
