import Head from "next/head";
import React from "react";
import Layout from "../components/Layout";
import ProjectItem from "../components/projects/ProjectItem";
import { DATABASE_ID, TOKEN } from "../config";

export default function project({ projects }) {
    return (
        <Layout>
            <div className="flex flex-col items-center justify-center min-h-screen px-3 mb-10">
                <Head>
                    <title>포트폴리오</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <h1>
                    총 프로젝트 : <span className="pl-4 text-blue-500">{projects.results.length}</span>
                </h1>

                <div className="grid grid-cols-1 gap-8 p-12 m-4 md:grid-cols-2">
                    {projects.results?.map((aProject) => (
                        <ProjectItem key={aProject.id} data={aProject} />
                    ))}
                </div>
            </div>
        </Layout>
    );
}

export async function getServerSideProps() {
    const options = {
        method: "POST",
        headers: { Authorization: `Bearer ${TOKEN}`, accept: "application/json", "Notion-Version": "2022-06-28", "content-type": "application/json" },

        body: JSON.stringify({
            sorts: [
                {
                    property: "Name",
                    direction: "ascending",
                },
            ],
            page_size: 100,
        }),
    };

    const res = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, options);
    const projects = await res.json();

    return {
        props: { projects }, // will be passed to the page component as props
    };
}
